# Generated by Django 5.1.5 on 2025-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='noticed_date',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
